//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPA_DATOS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CAPACITACIONEntities : DbContext
    {
        public CAPACITACIONEntities()
            : base("name=CAPACITACIONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cargo> cargo { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
    
        public virtual int SP_TB_CARGO_INSERT(string nOMBRE_CARGO, string dESCRIPCION_CARGO)
        {
            var nOMBRE_CARGOParameter = nOMBRE_CARGO != null ?
                new ObjectParameter("NOMBRE_CARGO", nOMBRE_CARGO) :
                new ObjectParameter("NOMBRE_CARGO", typeof(string));
    
            var dESCRIPCION_CARGOParameter = dESCRIPCION_CARGO != null ?
                new ObjectParameter("DESCRIPCION_CARGO", dESCRIPCION_CARGO) :
                new ObjectParameter("DESCRIPCION_CARGO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_CARGO_INSERT", nOMBRE_CARGOParameter, dESCRIPCION_CARGOParameter);
        }
    
        public virtual ObjectResult<cargo> SP_CARGO_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cargo>("SP_CARGO_GetAll");
        }
    
        public virtual ObjectResult<cargo> SP_CARGO_GetAll(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<cargo>("SP_CARGO_GetAll", mergeOption);
        }
    
        public virtual int SP_TB_Categoria_INSERT(string cODIGO_CATEGORIA, string nOMBRE_CATEGORIA)
        {
            var cODIGO_CATEGORIAParameter = cODIGO_CATEGORIA != null ?
                new ObjectParameter("CODIGO_CATEGORIA", cODIGO_CATEGORIA) :
                new ObjectParameter("CODIGO_CATEGORIA", typeof(string));
    
            var nOMBRE_CATEGORIAParameter = nOMBRE_CATEGORIA != null ?
                new ObjectParameter("NOMBRE_CATEGORIA", nOMBRE_CATEGORIA) :
                new ObjectParameter("NOMBRE_CATEGORIA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TB_Categoria_INSERT", cODIGO_CATEGORIAParameter, nOMBRE_CATEGORIAParameter);
        }
    }
}
